/**
 * Colours and options sourced from Global Suzuki 360° viewer JSON.
 * @see https://www.globalsuzuki.com/automobile/
 * Generated by scripts/extract-suzuki-viewer-colors.mjs — do not edit manually.
 */
import type { ConfiguratorData } from './demo-configurator';
import {
  BODY_COLOR_HEX_MAP,
  INTERIOR_COLOR_HEX_MAP,
  TWO_TONE_HEX_MAP,
} from './exterior-360-color-map';

export type SuzukiViewerColor = {
  id: string;
  name: string;
  thumbnail: string;
  swatch?: string;
  price: number;
};

export type SuzukiViewerOption = {
  id: string;
  name: string;
  description?: string;
  price: number;
  category: string;
};

export const suzukiViewerCatalog: Record<string, ConfiguratorData> = {
  "vitara": {
    "bodyColors": [
      {
        "id": "bc-26u",
        "name": "White",
        "thumbnail": "BC_26U",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_26U",
        "swatch": "/configurator/swatches/vitara/BC_26U.png"
      },
      {
        "id": "bc-zcc",
        "name": "Silky Silver Metallic",
        "thumbnail": "BC_ZCC",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_ZCC",
        "swatch": "/configurator/swatches/vitara/BC_ZCC.png"
      },
      {
        "id": "bc-zcd",
        "name": "Galactic Gray Metallic",
        "thumbnail": "BC_ZCD",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_ZCD",
        "swatch": "/configurator/swatches/vitara/BC_ZCD.png"
      },
      {
        "id": "bc-zce",
        "name": "Cosmic Black Pearl Metallic",
        "thumbnail": "BC_ZCE",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_ZCE",
        "swatch": "/configurator/swatches/vitara/BC_ZCE.png"
      },
      {
        "id": "bc-zcf",
        "name": "Bright Red",
        "thumbnail": "BC_ZCF",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_ZCF",
        "swatch": "/configurator/swatches/vitara/BC_ZCF.png"
      },
      {
        "id": "bc-znl",
        "name": "Cool White Pearl",
        "thumbnail": "BC_ZNL",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_ZNL",
        "swatch": "/configurator/swatches/vitara/BC_ZNL.png"
      },
      {
        "id": "bc-zqn",
        "name": "Atlantis Turquoise Pearl Metallic",
        "thumbnail": "BC_ZQN",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_ZQN",
        "swatch": "/configurator/swatches/vitara/BC_ZQN.png"
      },
      {
        "id": "bc-a9g-r",
        "name": "Galactic Gray Metallic+ Cosmic Black Pearl Metallic",
        "thumbnail": "BC_A9G_R",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_A9G_R",
        "swatch": "/configurator/swatches/vitara/BC_A9G_R.png"
      },
      {
        "id": "bc-a9h-r",
        "name": "Bright Red + Cosmic Black Pearl Metallic",
        "thumbnail": "BC_A9H_R",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_A9H_R",
        "swatch": "/configurator/swatches/vitara/BC_A9H_R.png"
      },
      {
        "id": "bc-a6h-r",
        "name": "Atlantis Turquoise Pearl Metallic + White",
        "thumbnail": "BC_A6H_R",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_A6H_R",
        "swatch": "/configurator/swatches/vitara/BC_A6H_R.png"
      },
      {
        "id": "bc-a9l-r",
        "name": "Atlantis Turquoise Pearl Metallic + Cosmic Black Pearl Metallic",
        "thumbnail": "BC_A9L_R",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_A9L_R",
        "swatch": "/configurator/swatches/vitara/BC_A9L_R.png"
      },
      {
        "id": "bc-a9n-r",
        "name": "Savanna Ivory Metallic + Cosmic Black Pearl Metallic",
        "thumbnail": "BC_A9N_R",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_A9N_R",
        "swatch": "/configurator/swatches/vitara/BC_A9N_R.png"
      },
      {
        "id": "bc-dbh-r",
        "name": "Solar Yellow Pearl Metallic / Cosmic Black Pearl Metallic",
        "thumbnail": "BC_DBH_R",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_DBH_R",
        "swatch": "/configurator/swatches/vitara/BC_DBH_R.png"
      },
      {
        "id": "bc-dbg-r",
        "name": "Solar Yellow Pearl Metallic / White",
        "thumbnail": "BC_DBG_R",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_DBG_R",
        "swatch": "/configurator/swatches/vitara/BC_DBG_R.png"
      },
      {
        "id": "bc-dbf-r",
        "name": "Ice Grayish Blue Metallic / Cosmic Black Pearl Metallic",
        "thumbnail": "BC_DBF_R",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_DBF_R",
        "swatch": "/configurator/swatches/vitara/BC_DBF_R.png"
      }
    ],
    "interiorColors": [
      {
        "id": "intbase-001",
        "name": "GLX",
        "thumbnail": "INTBASE_001",
        "price": 0,
        "swatch": "/configurator/swatches/vitara/INTBASE_001.png"
      },
      {
        "id": "intbase-002",
        "name": "GL+",
        "thumbnail": "INTBASE_002",
        "price": 0,
        "swatch": "/configurator/swatches/vitara/INTBASE_002.png"
      }
    ],
    "options": [
      {
        "id": "a-001",
        "name": "Outside door mirrors (molded-in colour)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "c-001",
        "name": "Turn signal lamp with body",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "e-001",
        "name": "DRL (Halogen)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "h-001",
        "name": "Roo rails (Black)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "i-001",
        "name": "Panoramic sunroof",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "j-001",
        "name": "Privacy glass",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "j-002",
        "name": "Privacy glass",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "k-001",
        "name": "DSBS (Dual Sensor Brake Support)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "m-001",
        "name": "Outside door handles",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "n-001",
        "name": "All GRIP emblem",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "o-001",
        "name": "Urban package",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "p-001",
        "name": "Rugged package",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "q-001",
        "name": "Front grille fins",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "r-001",
        "name": "Front grille upper accent line (Red)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "r-002",
        "name": "Front grille upper accent line (Black)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "s-001",
        "name": "Front bumper centre accent line (Red)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "s-002",
        "name": "Front bumper centre accent line (Black)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "t-001",
        "name": "Front Bumper Garnish and Front Skid Plate Set",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "u-001",
        "name": "DRL accent line (Red)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "u-002",
        "name": "DRL accent line (Black)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "w-001",
        "name": "Door mirror cover (Red)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "w-002",
        "name": "Door mirror cover (White)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "x-001",
        "name": "Side body moulding",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "y-001",
        "name": "Side fender garnish (Red)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "y-002",
        "name": "Side fender garnish (Black)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "z-001",
        "name": "Rear hatch moulding",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "aa-001",
        "name": "Rear bumper accent line (Red)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "aa-002",
        "name": "Rear bumper accent line (Black)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "ab-001",
        "name": "Rear skid plate",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "ac-001",
        "name": "Roof edge spoiler",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "ae-001",
        "name": "Centre cap (Red)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "ae-002",
        "name": "Centre cap (Black)",
        "price": 0,
        "category": "Exterior"
      }
    ]
  },
  "jimny": {
    "bodyColors": [
      {
        "id": "bc-dg52-r",
        "name": "Kinetic Yellow + Bluish Black Pearl 3",
        "thumbnail": "BC_DG52_R",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_DG52_R",
        "swatch": "/configurator/swatches/jimny/BC_DG52_R.png"
      },
      {
        "id": "bc-czw2-r",
        "name": "Brisk Blue Metallic + Bluish Black Pearl 3",
        "thumbnail": "BC_CZW2_R",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_CZW2_R",
        "swatch": "/configurator/swatches/jimny/BC_CZW2_R.png"
      },
      {
        "id": "bc-2bw2-r",
        "name": "Chiffon Ivory Metallic + Bluish Black Pearl 3",
        "thumbnail": "BC_2BW2_R",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_2BW2_R",
        "swatch": "/configurator/swatches/jimny/BC_2BW2_R.png"
      },
      {
        "id": "bc-zzc",
        "name": "Jungle Green",
        "thumbnail": "BC_ZZC",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_ZZC",
        "swatch": "/configurator/swatches/jimny/BC_ZZC.png"
      },
      {
        "id": "bc-zj3",
        "name": "Bluish Black Pearl 3",
        "thumbnail": "BC_ZJ3",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_ZJ3",
        "swatch": "/configurator/swatches/jimny/BC_ZJ3.png"
      },
      {
        "id": "bc-zvl",
        "name": "Medium Gray",
        "thumbnail": "BC_ZVL",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_ZVL",
        "swatch": "/configurator/swatches/jimny/BC_ZVL.png"
      },
      {
        "id": "bc-z2s",
        "name": "Silky Silver Metallic",
        "thumbnail": "BC_Z2S",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_Z2S",
        "swatch": "/configurator/swatches/jimny/BC_Z2S.png"
      },
      {
        "id": "bc-26u",
        "name": "White",
        "thumbnail": "BC_26U",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_26U",
        "swatch": "/configurator/swatches/jimny/BC_26U.png"
      }
    ],
    "interiorColors": [
      {
        "id": "intbase-001",
        "name": "GLX",
        "thumbnail": "INTBASE_001",
        "price": 0,
        "swatch": "/configurator/swatches/jimny/INTBASE_001.png"
      }
    ],
    "options": [
      {
        "id": "i-001",
        "name": "Front bumper under garnish",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "j-001",
        "name": "Side under garnish",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "m-001",
        "name": "Side body moulding",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "k-001",
        "name": "Mud flap front, red",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "n-001",
        "name": "Mud flap rear, red",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "o-001",
        "name": "Mud flap front, black",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "p-001",
        "name": "Mud flap rear, black",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "l-001",
        "name": "Spare tyre cover rigid (GLX)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "r-001",
        "name": "Multi roof rack",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "q-001",
        "name": "Roof basket",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "s-001",
        "name": "Rain and wind deflector set",
        "price": 0,
        "category": "Exterior"
      }
    ]
  },
  "swift": {
    "bodyColors": [
      {
        "id": "bc-e6l",
        "name": "Frontier Blue Pearl Metallic × Super Black Pearl",
        "thumbnail": "BC_E6L",
        "price": 0,
        "materialKey": "EXT-GRD_GL-BG_A-BC_E6L",
        "swatch": "/configurator/swatches/swift/BC_E6L.png"
      },
      {
        "id": "bc-d7z",
        "name": "Burning Red Pearl Metallic × Super Black Pearl",
        "thumbnail": "BC_D7Z",
        "price": 0,
        "materialKey": "EXT-GRD_GL-BG_A-BC_D7Z",
        "swatch": "/configurator/swatches/swift/BC_D7Z.png"
      },
      {
        "id": "bc-e6p",
        "name": "Cool Yellow Metallic × Mineral Gray Metallic",
        "thumbnail": "BC_E6P",
        "price": 0,
        "materialKey": "EXT-GRD_GL-BG_A-BC_E6P",
        "swatch": "/configurator/swatches/swift/BC_E6P.png"
      },
      {
        "id": "bc-dyh",
        "name": "Pure White Pearl × Mineral Gray Metallic",
        "thumbnail": "BC_DYH",
        "price": 0,
        "materialKey": "EXT-GRD_GL-BG_A-BC_DYH",
        "swatch": "/configurator/swatches/swift/BC_DYH.png"
      },
      {
        "id": "bc-wb1-r",
        "name": "Frontier Blue Pearl Metallic",
        "thumbnail": "BC_WB1_R",
        "price": 0,
        "materialKey": "EXT-GRD_GL-BG_A-BC_WB1_R",
        "swatch": "/configurator/swatches/swift/BC_WB1_R.png"
      },
      {
        "id": "bc-wb2-r",
        "name": "Cool Yellow Metallic",
        "thumbnail": "BC_WB2_R",
        "price": 0,
        "materialKey": "EXT-GRD_GL-BG_A-BC_WB2_R",
        "swatch": "/configurator/swatches/swift/BC_WB2_R.png"
      },
      {
        "id": "bc-zwp-r",
        "name": "Burning Red Pearl Metallic",
        "thumbnail": "BC_ZWP_R",
        "price": 0,
        "materialKey": "EXT-GRD_GL-BG_A-BC_ZWP_R",
        "swatch": "/configurator/swatches/swift/BC_ZWP_R.png"
      },
      {
        "id": "bc-zwd-r",
        "name": "Flame Orange Pearl Metallic",
        "thumbnail": "BC_ZWD_R",
        "price": 0,
        "materialKey": "EXT-GRD_GL-BG_A-BC_ZWD_R",
        "swatch": "/configurator/swatches/swift/BC_ZWD_R.png"
      },
      {
        "id": "bc-zyl-r",
        "name": "Caravan Ivory Pearl Metallic",
        "thumbnail": "BC_ZYL_R",
        "price": 0,
        "materialKey": "EXT-GRD_GL-BG_A-BC_ZYL_R",
        "swatch": "/configurator/swatches/swift/BC_ZYL_R.png"
      },
      {
        "id": "bc-zvr-r",
        "name": "Pure White Pearl",
        "thumbnail": "BC_ZVR_R",
        "price": 0,
        "materialKey": "EXT-GRD_GL-BG_A-BC_ZVR_R",
        "swatch": "/configurator/swatches/swift/BC_ZVR_R.png"
      },
      {
        "id": "bc-znc-r",
        "name": "Premium Silver Metallic",
        "thumbnail": "BC_ZNC_R",
        "price": 0,
        "materialKey": "EXT-GRD_GL-BG_A-BC_ZNC_R",
        "swatch": "/configurator/swatches/swift/BC_ZNC_R.png"
      },
      {
        "id": "bc-zmw-r",
        "name": "Mineral Gray Metallic",
        "thumbnail": "BC_ZMW_R",
        "price": 0,
        "materialKey": "EXT-GRD_GL-BG_A-BC_ZMW_R"
      },
      {
        "id": "bc-zmv-r",
        "name": "Super Black Pearl",
        "thumbnail": "BC_ZMV_R",
        "price": 0,
        "materialKey": "EXT-GRD_GL-BG_A-BC_ZMV_R",
        "swatch": "/configurator/swatches/swift/BC_ZMV_R.png"
      }
    ],
    "interiorColors": [
      {
        "id": "intbase-001",
        "name": "GLX",
        "thumbnail": "INTBASE_001",
        "price": 0,
        "swatch": "/configurator/swatches/swift/INTBASE_001.png"
      }
    ],
    "options": [
      {
        "id": "decal-001",
        "name": "Body decal set black （Casual sport）",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "decal-002",
        "name": "Body decal set grey （Casual sport）",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "decal-003",
        "name": "Body decal set black （Hard sport）",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "decal-004",
        "name": "Body decal set grey （Hard sport）",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "mirror-002",
        "name": "Door mirror cover (Red)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "mirror-006",
        "name": "Door mirror cover (Black)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "cover-002",
        "name": "Door mirror cover (Carbon fiber look)",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "bumper-001",
        "name": "Rear bumper protection film",
        "price": 0,
        "category": "Exterior"
      }
    ]
  },
  "s-cross": {
    "bodyColors": [
      {
        "id": "bc-zzz",
        "name": "Titan Dark Gray Pearl Metallic",
        "thumbnail": "BC_ZZZ",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_ZZZ"
      },
      {
        "id": "bc-26u",
        "name": "White",
        "thumbnail": "BC_26U",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_26U"
      },
      {
        "id": "bc-znl",
        "name": "Cool White Pearl",
        "thumbnail": "BC_ZNL",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_ZNL",
        "swatch": "/configurator/swatches/s-cross/BC_ZNL.png"
      },
      {
        "id": "bc-zcc",
        "name": "Silky Silver Metallic",
        "thumbnail": "BC_ZCC",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_ZCC",
        "swatch": "/configurator/swatches/s-cross/BC_ZCC.png"
      },
      {
        "id": "bc-zce",
        "name": "Cosmic Black Pearl Metallic",
        "thumbnail": "BC_ZCE",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_ZCE"
      },
      {
        "id": "bc-zq5",
        "name": "Energetic Red Pearl",
        "thumbnail": "BC_ZQ5",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_ZQ5",
        "swatch": "/configurator/swatches/s-cross/BC_ZQ5.png"
      },
      {
        "id": "bc-zq3",
        "name": "Canyon Brown Pearl Metallic",
        "thumbnail": "BC_ZQ3",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_ZQ3",
        "swatch": "/configurator/swatches/s-cross/BC_ZQ3.png"
      },
      {
        "id": "bc-zq4",
        "name": "Sphere Blue Pearl",
        "thumbnail": "BC_ZQ4",
        "price": 0,
        "materialKey": "EXT-GRD_GLX-BG_A-BC_ZQ4",
        "swatch": "/configurator/swatches/s-cross/BC_ZQ4.png"
      }
    ],
    "interiorColors": [
      {
        "id": "intbase-001",
        "name": "GLX",
        "thumbnail": "INTBASE_001",
        "price": 0,
        "swatch": "/configurator/swatches/s-cross/INTBASE_001.png"
      }
    ],
    "options": [
      {
        "id": "front3-skid-plate-001",
        "name": "Front skid plate",
        "price": 0,
        "category": "Exterior"
      },
      {
        "id": "rear-skid-plate-001",
        "name": "Rear skid plate",
        "price": 0,
        "category": "Exterior"
      }
    ]
  }
} as const;

function enrichColors<T extends { thumbnail?: string; hex?: string; hexSecondary?: string }>(
  colors: T[],
  hexMap?: Record<string, string>,
  twoToneMap?: Record<string, [string, string]>,
): T[] {
  return colors.map((color) => {
    if (!color.thumbnail) return color;

    const twoTone = twoToneMap?.[color.thumbnail];
    if (twoTone) {
      return {
        ...color,
        hex: color.hex ?? twoTone[0],
        hexSecondary: color.hexSecondary ?? twoTone[1],
      };
    }

    const hex = hexMap?.[color.thumbnail];
    if (hex && !color.hex) {
      return { ...color, hex };
    }

    return color;
  });
}

export function getSuzukiViewerData(modelSlug: string): ConfiguratorData | undefined {
  const data = suzukiViewerCatalog[modelSlug];
  if (!data) return undefined;

  return {
    ...data,
    bodyColors: enrichColors(
      data.bodyColors,
      BODY_COLOR_HEX_MAP[modelSlug],
      TWO_TONE_HEX_MAP[modelSlug],
    ),
    interiorColors: enrichColors(
      data.interiorColors,
      INTERIOR_COLOR_HEX_MAP[modelSlug],
    ),
  };
}
